version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/.github/workflows/requirements"
    schedule:
      interval: "monthly"
