{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hubcast.fullname" . }}
  labels:
    {{- include "hubcast.labels" . | nindent 4 }}
type: Opaque
data:
  # Secret keys match environment variable names for use with envFrom
  HC_GH_WEBHOOK_SECRET: {{ .Values.secrets.githubWebhookSecret | b64enc | quote }}
  HC_GH_PRIVATE_KEY: {{ .Values.secrets.githubPrivateKey | b64enc | quote }}
  HC_GL_WEBHOOK_SECRET: {{ .Values.secrets.gitlabWebhookSecret | b64enc | quote }}
  HC_GL_TOKEN: {{ .Values.secrets.gitlabToken | b64enc | quote }}
  {{- if .Values.secrets.ldapBindPassword }}
  HC_ACCOUNT_MAP_BIND_PASSWORD: {{ .Values.secrets.ldapBindPassword | b64enc | quote }}
  {{- end }}
{{- end }}
