import logging
import urllib.parse
from typing import Any, Literal

import aiohttp
import gidgetlab.aiohttp

from hubcast.clients.gitlab.auth import (
    GitLabAuthenticator,
    GitLabSingleUserAuthenticator,
)
from hubcast.exceptions import HubcastError, WebhookPermissionError
from hubcast.webhook import RoutingToken

log = logging.getLogger(__name__)


class GitLabClientFactory:
    def __init__(
        self,
        instance_url: str,
        requester: str,
        token: str,
        callback_url: str,
        webhook_secret: str,
        token_type: str = "impersonation",  # nosec B107
    ):
        self.requester = requester

        if token_type == "single":  # nosec B105
            self.auth = GitLabSingleUserAuthenticator(token)
        elif token_type == "impersonation":  # nosec B105
            self.auth = GitLabAuthenticator(instance_url, requester, token)
        else:
            raise ValueError(f"Unknown GitLab token type: {token_type}")

        self.instance_url = instance_url
        self.callback_url = callback_url
        self.webhook_secret = webhook_secret

    def create_client(self, user: str) -> "GitLabClient":
        """creates a GitLabClient for a specific user"""
        return GitLabClient(
            self.auth,
            self.requester,
            self.instance_url,
            self.callback_url,
            self.webhook_secret,
            user,
        )


class GitLabClient:
    def __init__(
        self,
        auth: GitLabAuthenticator | GitLabSingleUserAuthenticator,
        requester: str,
        instance_url: str,
        callback_url: str,
        webhook_secret: str,
        user: str,
    ):
        self.auth = auth
        self.requester = requester
        self.instance_url = instance_url
        self.callback_url = callback_url
        self.webhook_secret = webhook_secret
        self.user = user

    async def get_mr(
        self, gl_fullname: str, src_branch: str, target_branch: str
    ) -> list[dict[str, Any]]:
        gl_token = await self.auth.authenticate_user(self.user)

        async with aiohttp.ClientSession() as session:
            gl = gidgetlab.aiohttp.GitLabAPI(
                session,
                requester=self.requester,
                access_token=gl_token,
                url=self.instance_url,
            )

            repo_id = urllib.parse.quote_plus(gl_fullname)
            filters = (
                f"source_branch={src_branch}&target_branch={target_branch}&state=opened"
            )

            return await gl.getitem(f"/projects/{repo_id}/merge_requests?{filters}")

    async def create_mr(
        self,
        gl_fullname: str,
        src_branch: str,
        target_branch: str,
        ref_title: int,
        ref_url: str,
    ):
        """Create a merge request in GitLab.

        Args:
            gl_fullname: GitLab project name
            src_branch: Source branch for the MR
            target_branch: Target (base) branch for the MR
            ref_title: GitHub PR title
            ref_url: GitHub PR URL to include in the MR description
        """
        gl_token = await self.auth.authenticate_user(username=self.user)

        async with aiohttp.ClientSession() as session:
            gl = gidgetlab.aiohttp.GitLabAPI(
                session,
                requester=self.requester,
                access_token=gl_token,
                url=self.instance_url,
            )

            repo_id = urllib.parse.quote_plus(gl_fullname)

            await gl.post(
                f"/projects/{repo_id}/merge_requests",
                data={
                    "source_branch": src_branch,
                    "target_branch": target_branch,
                    "title": ref_title,
                    "description": ref_url,
                },
            )

    async def set_webhook(
        self,
        dest_org: str,
        dest_repo: str,
        gh_owner: str,
        gh_repo: str,
        gh_check: str,
        check_types: list[Literal["pipeline", "child-pipelines", "jobs"]],
    ) -> None:
        gl_token = await self.auth.authenticate_user(username=self.user)
        gl_fullname = f"{dest_org}/{dest_repo}"

        # Generate unique signed token for this webhook containing routing information
        routing_token = RoutingToken(
            gh_owner=gh_owner,
            gh_repo=gh_repo,
            gh_check=gh_check,
            check_types=check_types,
        )
        token = routing_token.encode(self.webhook_secret)

        new_hook = {
            "token": token,
            "url": self.callback_url,
            "name": "hubcast",
            "description": "Generated by Hubcast for status reporting.",
            "job_events": "jobs" in check_types,
            "pipeline_events": any(
                check_type in check_types
                for check_type in ("pipeline", "child-pipelines")
            ),
            "push_events": False,
        }

        async with aiohttp.ClientSession() as session:
            gl = gidgetlab.aiohttp.GitLabAPI(
                session,
                requester=self.requester,
                access_token=gl_token,
                url=self.instance_url,
            )

            repo_id = urllib.parse.quote_plus(gl_fullname)
            url = f"/projects/{repo_id}/hooks"
            try:
                hooks_data = await gl.getitem(url)
            except gidgetlab.exceptions.BadRequest as exc:
                if exc.status_code == 403:
                    raise WebhookPermissionError(
                        "User cannot access GitLab webhooks; must have `maintainer` role."
                    ) from exc
                elif exc.status_code == 401:
                    # the user never supplies this token; a rejection means
                    # hubcast's own credential setup is broken
                    raise HubcastError(
                        "GitLab rejected hubcast's token while setting webhook - check hubcast's GitLab credentials",
                    ) from exc
                raise

            existing_hook = None
            for hook in hooks_data:
                if hook["name"] == "hubcast":
                    existing_hook = hook
                    break

            # if no existing hook is found add one and exit
            if not existing_hook:
                await gl.post(url, data=new_hook)
                return

            # otherwise update the existing hook with the new config
            url = f"/projects/{repo_id}/hooks/{existing_hook['id']}"
            await gl.put(url, data=new_hook)

    async def get_pipeline(self, gl_fullname: str, pipeline_id: int) -> dict:
        """Gets a pipeline object for a GitLab project."""

        gl_token = await self.auth.authenticate_user(self.user)

        async with aiohttp.ClientSession() as session:
            gl = gidgetlab.aiohttp.GitLabAPI(
                session,
                requester=self.requester,
                access_token=gl_token,
                url=self.instance_url,
            )

            repo_id = urllib.parse.quote_plus(gl_fullname)

            return await gl.getitem(f"/projects/{repo_id}/pipelines/{pipeline_id}")

    async def get_latest_pipeline(self, gl_fullname: str, ref: str) -> int:
        """gets the latest pipeline for an arbitrary GitLab repository and branch.
        Returns:
            the pipeline's id
        """

        gl_token = await self.auth.authenticate_user(self.user)

        async with aiohttp.ClientSession() as session:
            gl = gidgetlab.aiohttp.GitLabAPI(
                session,
                requester=self.requester,
                access_token=gl_token,
                url=self.instance_url,
            )

            repo_id = urllib.parse.quote_plus(gl_fullname)

            pipeline = await gl.getitem(
                f"/projects/{repo_id}/pipelines/latest?ref={ref}"
            )

            return pipeline.get("id")

    async def run_pipeline(self, gl_fullname: str, ref: str) -> str:
        """(re)-run a pipeline from an arbitrary GitLab repository and branch.
        Returns:
            the new pipeline's url
        """

        gl_token = await self.auth.authenticate_user(self.user)

        async with aiohttp.ClientSession() as session:
            gl = gidgetlab.aiohttp.GitLabAPI(
                session,
                requester=self.requester,
                access_token=gl_token,
                url=self.instance_url,
            )

            repo_id = urllib.parse.quote_plus(gl_fullname)

            pipeline = await gl.post(f"/projects/{repo_id}/pipeline?ref={ref}", data={})

            return pipeline.get("web_url")

    async def retry_pipeline_jobs(self, gl_fullname: str, pipeline_id: int) -> str:
        """retries any failed jobs in a pipeline. if there are no jobs that meet this criteria,
        calling this has no effect
        Returns:
            the pipeline's url
        """

        gl_token = await self.auth.authenticate_user(self.user)

        async with aiohttp.ClientSession() as session:
            gl = gidgetlab.aiohttp.GitLabAPI(
                session,
                requester=self.requester,
                access_token=gl_token,
                url=self.instance_url,
            )

            repo_id = urllib.parse.quote_plus(gl_fullname)

            pipeline = await gl.post(
                f"/projects/{repo_id}/pipelines/{pipeline_id}/retry", data={}
            )

            return pipeline.get("web_url")

    async def retry_job(self, gl_fullname: str, job_id: int) -> str:
        """retries a single job in a GitLab pipeline.
        Returns:
            the job's url
        """

        gl_token = await self.auth.authenticate_user(self.user)

        async with aiohttp.ClientSession() as session:
            gl = gidgetlab.aiohttp.GitLabAPI(
                session,
                requester=self.requester,
                access_token=gl_token,
                url=self.instance_url,
            )

            repo_id = urllib.parse.quote_plus(gl_fullname)

            job = await gl.post(f"/projects/{repo_id}/jobs/{job_id}/retry", data={})

            return job.get("web_url")

    async def get_commit(self, gl_fullname: str, sha: str) -> dict:
        """Get details for a commit SHA in a project"""
        gl_token = await self.auth.authenticate_user(self.user)

        async with aiohttp.ClientSession() as session:
            gl = gidgetlab.aiohttp.GitLabAPI(
                session,
                requester=self.requester,
                access_token=gl_token,
                url=self.instance_url,
            )

            repo_id = urllib.parse.quote_plus(gl_fullname)

            return await gl.getitem(f"/projects/{repo_id}/repository/commits/{sha}")
