name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      style: ${{ steps.filter.outputs.style }}
      security: ${{ steps.filter.outputs.security }}
      unit-tests: ${{ steps.filter.outputs.unit-tests }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # @v2
        if: ${{ github.event_name == 'push' }}
        with:
          fetch-depth: 0

        # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            style:
              - '.github/**/*'
              - 'src/**/*'
              - 'pyproject.toml'
            security:
              - '.github/**/*'
              - 'src/**/*'
              - 'pyproject.toml'
              - '.bandit'
           # unit-tests:
           #   - '.github/**/*'
           #   - 'src/**/*'
           #   - 'tests/**/*'
           #   - 'pyproject.toml'

  style:
    if: ${{ needs.changes.outputs.style == 'true' }}
    needs: changes
    uses: ./.github/workflows/style.yml

  security:
    if: ${{ needs.changes.outputs.security == 'true' }}
    needs: [changes, style]
    uses: ./.github/workflows/security.yml
    permissions:
      contents: read
      security-events: write

  # unit-tests:
  #   if: ${{ needs.changes.outputs.unit-tests == 'true' }}
  #   needs: [changes, style]
  #   uses: ./.github/workflows/unit-tests.yml

  # coverage:
  #   if: ${{ needs.changes.outputs.unit-tests == 'true' }}
  #   needs: [changes, style, unit-tests]
  #   uses: ./.github/workflows/coverage.yml

  all:
    needs:
     - changes
     - style
     - security
     # - unit-tests
     # - coverage
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Status summary
      run: |
        if ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}; then
          echo "One or more required jobs failed or were cancelled"
          exit 1
        else
          echo "All jobs completed successfully"
        fi
