name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      style: ${{ steps.filter.outputs.style }}
      run: ${{ steps.filter.outputs.run }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # @v2
        if: ${{ github.event_name == 'push' }}
        with:
          fetch-depth: 0

        # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: filter
        with:
          filters: |
            style:
              - '.github/**'
              - 'hubcast/**'
              - 'pyproject.toml'

  style:
    if: ${{ needs.changes.outputs.style == 'true' }}
    needs: changes
    uses: ./.github/workflows/style.yml
  test:
    runs-on: ubuntu-latest
    needs: style
    strategy:
      matrix:
        python-version: ['3.8', '3.11']
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          pip install --upgrade pip tox
      - name: Test with tox
        run: |
          tox -e ${{ matrix.python-version }}
