name: Helm Chart Validation
on:
  workflow_call:

permissions:
  contents: read

jobs:
  helm-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Set up Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310

      - name: Lint Helm Chart
        run: |
          helm lint helm/

      - name: Template Helm Chart (default values)
        run: |
          helm template hubcast helm/ > /dev/null

      - name: Template Helm Chart (OpenShift)
        run: |
          helm template hubcast helm/ -f helm/values-openshift.yaml > /dev/null

      - name: Template Helm Chart (OpenShift LDAP)
        run: |
          helm template hubcast helm/ -f helm/values-openshift-ldap.yaml > /dev/null
