name: Unit Tests
on:
  workflow_call:

permissions:
  contents: read

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.13']
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            'pyproject.toml'
            '.github/workflows/requirements/unit-tests.txt'

      - name: install python-ldap build dependencies
        # https://www.python-ldap.org/en/latest/installing.html#build-prerequisites
        # there are no wheels available, must build from source
        # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#administrative-privileges
        # sudo apt-get update
        run: |
          sudo apt-get install -y build-essential ldap-utils libldap2-dev libsasl2-dev

      - name: Install Python dependencies
        run: |
          pip install .
          pip install -r .github/workflows/requirements/unit-tests.txt

      - name: Run Unit Tests with Pytest
        run: |
          python3 -m build  # build package for compatibility with publish.yml
          python3 -m pytest
